name: Liquibase_Docker_GitHub-Hosted

on:
  workflow_dispatch:
   push:
     branches: [ main ]

#env:
    #LIQUIBASE_PRO_LICENSE_KEY: ${{ secrets.LB_PROKEY }}
    #LIQUIBASE_COMMAND_CHANGELOG_FILE: ${{ secrets.LB_CLFILE }}

jobs:
  SnowflakeLBDocker:
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v2
    
    - name: Run Liquibase status
      uses: docker://liquibase/liquibase:snowflake
      with:
        args: --changeLogFile=.Changelogs/snowflake1.xml checks run